spring.config.import=optional:file:.env[.properties]

spring.application.name=Product-Manager
spring.profiles.active=dev

spring.graphql.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4321}
# PostgreSQL datasource composed from .env values
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:products}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
